name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn run build
      # - name: Deploy files via FTP
      #   uses: appleboy/ftp-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_USERNAME }}
      #     username: ${{ secrets.DEPLOY_USERNAME }}
      #     password: ${{ secrets.DEPLOY_PASSWORD }}
      #     local-dir: build
      #     remote-dir: ${{ secrets.DEPLOY_PATH }}
